### ISSUE TITLE
Support custom exceptions?

### ISSUE THREAD

**Issue by elbbub** [richpeck/exception_handler#30]
Hi,

How to response to a custom exception?

**Comment by richpeck** [comment]
Hi bud, can you give me a use case? This will have to be added - I have a new solution lined up & ready to deploy, I can add this feature if required

**Comment by elbbub** [comment]
Sure, such catching a custom exception like MyException and redirect or render a custom view as well.

**Comment by richpeck** [comment]
So I found how to do this → [`config.action_dispatch.rescue_responses`](http://guides.rubyonrails.org/configuring.html#configuring-action-dispatch) ↴

![custom_exceptions](https://cloud.githubusercontent.com/assets/1104431/21762425/8281d54e-d650-11e6-9587-db0a8b058ef6.jpg)
---

Because browsers work on `HTTP`, the only errors we're able to *return* are `40x` and `50x`.

The exceptions we raise internally can be anything; in order for the browser to understand what is happening, they need to be mapped to one of the corresponding error codes:

![HTTP Error Codes](https://i.stack.imgur.com/5xfqA.png)

The way to do this is by mapping our exceptions to a corresponding HTTP error code:

```
# config/application.rb
config.action_dispatch.rescue_responses["ActionController::CustomException"] = :bad_request
```

This is already pre-baked into Rails so I don't see how supporting it in `ExceptionHandler` would make things easier. I suppose I could make a simple crossover option in config to map the requests, but in reality it will just be adding to the `rescue_responses` code...

```
config.exception_handler = {
  custom_exceptions: {
    "ActionController::CustomException" => :bad_request
  }
}
```
---

In regard serving specific layouts / views, what I can do is split the view / layout picker to depend on the HTTP error code table specifically. Since we can only return `40x` / `50x` errors, perhaps we could make the choice of layout for those errors specifically, such as:

```
config.exception_handler = {
  layouts: {
    bad_gateway: "xyz"
  }
}
```

Will be interesting to hear your thoughts on it.
