### ISSUE TITLE
Not working with Heroku?

### ISSUE THREAD

**Issue by lucasgerard** [richpeck/exception_handler#37]
Hi, the gem 0.5.1 is working fine locally - great work! - however it does not catch any exceptions when I deploy to Heroku. Any clue? Rails version is 4.2 and ruby-2.2.4

Cheers!

**Comment by richpeck** [comment]
Do you have a link to the heroku app? Also could you post any logs for the expected exception?

Thanks :)

**Comment by lucasgerard** [comment]
Hi, thanks for the quick reply!

Here is a link to a bugged page: https://jetaide-tests.herokuapp.com/about/index, and the expection is stated clearly ;)

Good to know that it is well catched locally

**Comment by lucasgerard** [comment]
![screen shot 2016-09-23 at 15 50 48](https://cloud.githubusercontent.com/assets/5589858/18788026/8b9965ca-81a5-11e6-87f4-9680fb2d282c.png)

**Comment by richpeck** [comment]
No problem, merci pour votre user de le gem ;)

Mon francais est trop petite pour un conversation, donc j'écrirai en Anglais...

---

**1. L'erreur**

Sur Heroku, l'app should not be showing the "naked" error. 

Have you switched something in the `config/environment/production.rb` files to make it so that it treats the app as development? Specifically, you need to make sure you have the following:

```
#app/config/environments/production.rb
config.consider_all_requests_local = false
```

If it's working locally, I can only surmise that you have some setting disabled in production - making it think that the app is running locally. Is this the case?

--

**2. Routes**

According to [resourceful routing](http://guides.rubyonrails.org/routing.html#customizing-resourceful-routes), your `/about/index` path should just be `/about`:

![untitledasdf](https://cloud.githubusercontent.com/assets/1104431/18794073/c13c137a-81b5-11e6-9701-c5a0b4138dda.png)


If you have manually designated the `/about/index` route, you may wish to use the following:

```
#config/routes.rb
# ...
# Put this at the very bottom of the routes file:
# This way, you can include other base routes without having pages interfering
# Rails checks the routes file sequentially, so the last routes are the last to be checked
resources :pages, path_name: "", only: :show # => http://site.com/:id => http://site.com/about
```

This will allow you to use `app/controllers/pages_controller.rb` as follows:

```
#app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find params[:id] #-> will need to use "friendly_id" to find by slug
  end
end
```

```
#app/views/pages/show.html.erb
<%= @page.content %>
```

--

**3. OOP**

Finally, you should *never* include "naked" calls in your view.

Rails is [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) -
 
  - `model` = data
  - `controller` = passes data from model to view
  - `view` = displays data

The view should only have references to `@instance` variables - making them as interchangeable as possible. Your call to `ActsAsTenant.current_tenant.user_about_howto_paragraph.html_safe` is not in line with convention.

What you *should* have is the following:

```
#app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
     @user = ActsAsTenant.current_tenant
  end
end

#app/views/pages/index.html.erb
<h3 class="lead">
      <!-- Never style with <br /> tags, add padding or margin to h3.leads if you want padding -->
      <%= @user.user_about_howto_paragraph.html_safe %>
</h3>
```

The *main* reason for this is that setting a single instance variable will mean you can call it multiple times, rather than using the "naked" data call each time - which will be pinging the database whenever you reference it.

-

As a bonus, if you switched to `haml`, you'd be able to use the following:

```
#app/views/pages/index.haml
%h3.lead
  = @user.user_about_howto_paragraph.html_safe
```

**Comment by lucasgerard** [comment]
Hey, point 1 solved my case, thanks ;)

Thank you as well for the general advice. Actually the project went through several hands and there is indeed plenty of space for optimization.

Thank you again for this great gem and your help!
