### ISSUE TITLE
What should I do with the files in public folder, e.g. 404.html etc

### ISSUE THREAD

**Issue by StarWar** [richpeck/exception_handler#42]
Hi, I've successfully integrated exception_handler gem. It's a nice gem.

But I still have files in public folders e.g. 404.html, 422.html and others. 
Should I remove these files? Or should I use curl and save the pretty version of these. How should I raise the correct error exceptions which exception_handler gem handles to generate 500, 422 and 404 pages at runtime on Heroku? or Should I just remove these pages?
Also, I need to remove assets provided by exception_handler, I'm using my own assets and it only increases the slug size.

Thanks,

**Comment by richpeck** [comment]
Hi Statwar, thanks for the kind words.

1. You can remove those - they are used by Rails as default but since EH overrides the default, they aren't required

2. Yes, you can remove the files. The standard Rails way is to route the exception to the routes, which in turn calls `500.html` etc. Because EH overrides them, you don't need them any more. We don't have them:

![untitled-1](https://cloud.githubusercontent.com/assets/1104431/22020532/bdf5e08c-dcb0-11e6-97ac-66d9d6ba573c.jpg)

3. EH adds `exception_handler.css` to the precompile list:

![untitled-1](https://cloud.githubusercontent.com/assets/1104431/22020640/2d111018-dcb1-11e6-9bc3-b089adc8f7a8.jpg)

This, in turn, adds the rest of the assets.

To remove these assets from precompilation, you'll need to use the following to your main app:

```
# config/application.rb
config.assets.precompile -= %w(exception_handler)
```

**I will push the latest version of the gem (`0.7.5`) which includes an updated `assets.precompile` reference.** It will only work with the update, which I'm working on pushing now for you.

**Comment by StarWar** [comment]
After updating to 0.7.5, local requests are not working. I have set dev: true and even set   config.consider_all_requests_local       = true
and It's still showing better error page.

**Comment by richpeck** [comment]
Thanks, which version of Rails are you using?

**Comment by StarWar** [comment]
Rails 4.2.7

**Comment by richpeck** [comment]
Have you got a repo I could clone?

**Comment by StarWar** [comment]
It's private, Can't share. It's showing the default message from exception handler and not my customized page on Heroku.

**Comment by richpeck** [comment]
I'm testing on 4.2.7 locally - I want to see what the issue is before changing. I can push the gem again so I need to make sure what's going on

**Comment by richpeck** [comment]
I think the issue is that the config var is not being populated

**Comment by richpeck** [comment]
If you invite me to your repo or even show me your Heroku page, I'll be in a much better position to test. I think the reason is because the `config` var is not being set but I cannot be sure until I see

**Comment by StarWar** [comment]
I reverted to the older version 0.7. And pages were behind login. Here's the page https://www.9curry.com/support
Error page https://www.9curry.com/supporterror
And when I update to 0.75 it shows only "Page missing" and not in my layout.

**Comment by richpeck** [comment]
Okay, thanks!

Alright so there are several potential issues.

1. We renamed the `exception_controller.rb` to [`exceptions_controller.rb` ](https://github.com/richpeck/exception_handler/blob/master/app/controllers/exception_handler/exceptions_controller.rb) - perhaps this is not being overridden)- if you've overridden the controller, you'll have to change it to `ExceptionHandler::ExceptionsController` (plural)

2. The layouts definitions have changed in the `config`. It used to be that `400` would override the layout for all `4xx` errors; now it has to be defined by error type specifically. For example:

```
config.exception_handler = {
  layouts: {
    400: "your_layout",
    401: "your_layout"
    404: "your_layout
  }
}
```

The layout thing is to ensure we are able to cover all potential errors, instead of just the standard issues. We are working on another change for this to make it even simpler still.

3. You don't really need to override the view unless you need specific CSS styling. The new view is extremely modular and doesn't have any external elements etc, it's very simple.

----

My offer still stands, if you invite me to your repo, I'll make some specific changes in a branch for you. 

I can't do anything to your site / business, and I don't want to anyway. I want EH to work well and this would be the best way to ensure that.
