### ISSUE TITLE
What to do with non html formats (missing images)?

### ISSUE THREAD

**Issue by mtomov** [richpeck/exception_handler#55]
Hello, thanks indeed for the great gem!

Have been struggling to figure out how to handle 404 pages for missing images and other non html, json or xml requests.

Currently, if I request `file.png`, then the Exception App handles the request and I get

```sql
Processing by ExceptionHandler::ExceptionController#show as PNG
Completed 500 Internal Server Error in 81ms (ActiveRecord: 3.6ms)

Error during failsafe response: Missing template exception_handler/exception/show, alchemy/base/show, application/show with {:locale=>[:en], :formats=>[:png], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rabl], :versions=>[:v10, :v9, :v8, :v7, :v6, :v5, :v4, :v3, :v2, :v1]}

Searched in:
```

If I use `respond_with` or `respond_to :html` in the controller, then I get

```sql
Processing by ExceptionHandler::ExceptionController#show as PNG

Completed 406 Not Acceptable in 16ms (ActiveRecord: 0.0ms)

Error during failsafe response: ActionController::UnknownFormat

```

.. and I get a 500 error in the browser instead of the 406 : (

Note, I'm using a slightly older version of the gem - `0.5.1`, but I don't think going with a newer version of it will make a difference, as I already tested out the latest exception controller with the `respond_with`. Rails is 4.2.

I have a feeling I am missing something, as I couldn't find anyone else complain about something similar. Any ideas?

Thank you

**Comment by richpeck** [comment]
Hi thanks for the post - sorry about the late response, for some reason I didn't get an email about this. Let me have a look for you

**Comment by richpeck** [comment]
I've had this before, except with `CSS` files.  

The problem is that Rails gets confused about the mime type.

What's happening is that whenever you send a `.x` file extension without having the correct file available, Rails is treating the erroneous request as being for the `.x` mime. Thus, it tries to search for the appropriate "view" for the mime... be it `exception_handler/exception/show.css` or `exception_handler/exception/show.png` in your case.

The way I "fixed" it was with a [catch-all](https://github.com/richpeck/exception_handler/blob/master/app/controllers/exception_handler/exceptions_controller.rb#L23)...

```
# exception_handler/controllers/exceptions_controller.rb

# => Response format (required for non-standard formats (.css / .gz etc))
# => request.format required until responders updates with wildcard / failsafe (:all)
before_action { |e| e.request.format = :html unless self.class.respond_to.include? e.request.format } 
```

Do you still have this in your controller?

**Comment by mtomov** [comment]
Ah, great one! Thanks a lot! 

I've read the previous 2 `before_action` blocks, but failed to read the code for this one, and I've missed it. 

Will put it in, and will confirm again that's working. Thanks a lot again for the clear answer!

**Comment by richpeck** [comment]
No problem, please keep me updated as to whether it works or not!

**Comment by mtomov** [comment]
Thanks again! I've upgraded to the latest version, and can confirm that it is indeed all working out correctly - with 404 page returned.

Thank you!
